### ISSUE TITLE
[Bug]: WAF IPset example does not work when passing addresses

### ISSUE THREAD

**Issue by ItaloChagas** [crossplane-contrib/provider-upjet-aws#1182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

wafv2.aws.upbound.io/v1beta1: IPSet

### Resource MRs required to reproduce the bug
```
apiVersion: wafv2.aws.upbound.io/v1beta1
kind: IPSet
metadata:
  annotations:
    meta.upbound.io/example-id: wafv2/v1beta1/ipset
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    addresses:
      - 1.2.3.4/32
      - 5.6.7.8/32
    description: Example IP set
    ipAddressVersion: IPV4
    name: example
    region: us-east-1
    scope: CLOUDFRONT
    tags:
      Tag1: Value1
      Tag2: Value2
```
### Steps to Reproduce

`kubectl apply` the provided yaml manifest above

### What happened?

Managed resource is created in the cluster, but there is no event when `kubectl describe ipset example`.
```
k get ipset example
NAME      READY   SYNCED   EXTERNAL-NAME   AGE
example                                    18m
```

### Relevant Error Output Snippet

```shell
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227
2024-02-29T18:21:14Z	DEBUG	provider-aws	Reconciling	{"controller": "managed/wafv2.aws.upbound.io/v1beta1, kind=ipset", "request": {"name":"example"}}
2024-02-29T18:21:14Z	DEBUG	provider-aws	Connecting to the service provider	{"uid": "d99afd99-7759-419e-aac5-4a6faff8c846", "name": "example", "gvk": "wafv2.aws.upbound.io/v1beta1, Kind=IPSet"}
2024-02-29T18:21:14Z	DEBUG	provider-aws	Instance state not found in cache, reconstructing...	{"uid": "d99afd99-7759-419e-aac5-4a6faff8c846", "name": "example", "gvk": "wafv2.aws.upbound.io/v1beta1, Kind=IPSet"}
2024-02-29T18:21:14Z	DEBUG	provider-aws	Observing the external resource	{"uid": "d99afd99-7759-419e-aac5-4a6faff8c846", "name": "example", "gvk": "wafv2.aws.upbound.io/v1beta1, Kind=IPSet"}
E0229 18:21:14.886926       1 runtime.go:79] Observed a panic: &runtime.TypeAssertionError{_interface:(*runtime._type)(0xe7f08a0), concrete:(*runtime._type)(nil), asserted:(*runtime._type)(0xe9d78c0), missingMethod:""} (interface conversion: interface {} is nil, not map[string]interface {})
goroutine 27262 [running]:
```
```


### Crossplane Version

v1.14.4

### Provider Version

v0.46.1

### Kubernetes Version

1.29

### Kubernetes Distribution

EKS

### Additional Info

I have tried create the resource with minimum parameters and it did work, but when passing the `addresses` the error occurs.

**Comment by turkenf** [comment]
Hi @ItaloChagas,

Thank you for raising this issue, I could not reproduce the issue with provider version `1.4.0`:
```
  Conditions:
    Last Transition Time:  2024-05-09T12:11:16Z
    Reason:                Available
    Status:                True
    Type:                  Ready
    Last Transition Time:  2024-05-09T12:11:13Z
    Reason:                ReconcileSuccess
    Status:                True
    Type:                  Synced
    Last Transition Time:  2024-05-09T12:11:14Z
    Reason:                Success
    Status:                True
    Type:                  LastAsyncOperation
Events:
  Type    Reason                   Age   From                                              Message
  ----    ------                   ----  ----                                              -------
  Normal  CreatedExternalResource  35s   managed/wafv2.aws.upbound.io/v1beta1, kind=ipset  Successfully requested creation of external resource
```

Could you please try with `v1.4.0` and let us know?
