### ISSUE TITLE
[Bug]: ec2 instance not ready and not syncing with `Observed a panic: value is null`

### ISSUE THREAD

**Issue by tyu0912** [crossplane-contrib/provider-upjet-aws#1579]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

ec2.aws.upbound.io/v1beta1 - Instance

### Resource MRs required to reproduce the bug

```
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Instance
metadata:
  labels:
    testing.upbound.io/example-name: platform-demo-test
  name: platform-demo-test
spec:
  # Instance configuration
  forProvider:
    ami: ami-0453ec754f44f9a4a
    instanceType: t2.micro
    region: us-east-1
    subnetId: <my-subnet>
  
  # Reference credentials
  providerConfigRef:
    name: default
```

### Steps to Reproduce

Following the guide here. The only difference is that I'm making an EC2 instance instead of S3. 

https://docs.crossplane.io/latest/getting-started/provider-aws/

### What happened?

Hi, this may be simple but while playing around with crossplane, the instance I create does get sync or get to a ready state even though on AWS, I can see it created

<img width="1035" alt="image" src="https://github.com/user-attachments/assets/40598147-2567-4a02-8e1b-d79652f863f5">

<img width="876" alt="image" src="https://github.com/user-attachments/assets/1f82189e-1c34-448b-8408-78038c259df6">

Error log from `provider-aws-ec2` pod 

```
E1128 23:15:17.869739       1 runtime.go:77] Observed a panic: value is null
goroutine 13029 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x175a9e60, 0x1db8faf0})
    k8s.io/apimachinery@v0.29.4/pkg/util/runtime/runtime.go:75 +0x7c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
    sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go:108 +0xa4
panic({0x175a9e60?, 0x1db8faf0?})
    runtime/panic.go:785 +0x124
github.com/hashicorp/go-cty/cty.Value.LengthInt({{{0x1dea7df8?, 0x4009ed6da0?}}, {0x0?, 0x0?}})
    github.com/hashicorp/go-cty@v1.4.1-0.20200723130312-85980079f637/cty/value_ops.go:989 +0x254
github.com/hashicorp/terraform-provider-aws/internal/tags.GetAnyAttr({{{0x1dea7d88?, 0x400ca97e30?}}, {0x181b02c0?, 0x40060cd6b0?}}, {0x1ab529a8, 0x19}, 0x0)
    github.com/hashicorp/terraform-provider-aws@v0.0.0-00010101000000-000000000000/internal/tags/key_value_tags.go:804 +0x2d8
github.com/hashicorp/terraform-provider-aws/internal/tags.KeyValueTags.ResolveDuplicates(0x400616b4d8, {0x1dea72b8, 0x4006554f30}, 0x0, 0x0, {0x1de9cf60, 0x400d6f1300}, {0x1ab529a8, 0x19}, 0x0)
    github.com/hashicorp/terraform-provider-aws@v0.0.0-00010101000000-000000000000/internal/tags/key_value_tags.go:834 +0x204
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.readBlockDevicesFromInstance({0x1dea72b8, 0x4006554f30}, 0x400d6f1300, {0x1aa07b40, 0x40074f95f0}, 0x4000bb0848, 0x0)
    github.com/hashicorp/terraform-provider-aws@v0.0.0-00010101000000-000000000000/internal/service/ec2/ec2_instance.go:2385 +0xe40
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.readBlockDevices({0x1dea72b8?, 0x4006554f30?}, 0x400d6f1300, {0x1aa07b40?, 0x40074f95f0?}, 0x0?, 0x0?)
    github.com/hashicorp/terraform-provider-aws@v0.0.0-00010101000000-000000000000/internal/service/ec2/ec2_instance.go:2240 +0x34
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.resourceInstanceRead({0x1dea72b8, 0x4006554f30}, 0x400d6f1300, {0x1aa07b40, 0x40074f95f0})
    github.com/hashicorp/terraform-provider-aws@v0.0.0-00010101000000-000000000000/internal/service/ec2/ec2_instance.go:1353 +0x23d0
github.com/hashicorp/terraform-provider-aws/internal/provider.New.(*wrappedResource).Read.interceptedHandler[...].func10(0x400d6f1300?, {0x1aa07b40?, 0x40074f95f0})
    github.com/hashicorp/terraform-provider-aws@v0.0.0-00010101000000-000000000000/internal/provider/intercept.go:113 +0x1d8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x1dea7360?, {0x1dea7360?, 0x400100c2a0?}, 0xd?, {0x1aa07b40?, 0x40074f95f0?})
    github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:818 +0x64
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0x40026e7a40, {0x1dea7360, 0x400100c2a0}, 0x400546f2b0, {0x1aa07b40, 0x40074f95f0})
    github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:1117 +0x404
github.com/crossplane/upjet/pkg/controller.(*terraformPluginSDKExternal).Observe(0x4001ada000, {0x1dea7360, 0x400100c2a0}, {0x1e02b7b8, 0x40021dea88})
    github.com/crossplane/upjet@v1.4.1-0.20240911184956-3afbb7796d46/pkg/controller/external_tfpluginsdk.go:472 +0x138
github.com/crossplane/upjet/pkg/controller.(*terraformPluginSDKAsyncExternal).Observe(0x40072174a0, {0x1dea7360, 0x400100c2a0}, {0x1e02b7b8, 0x40021dea88})
    github.com/crossplane/upjet@v1.4.1-0.20240911184956-3afbb7796d46/pkg/controller/external_async_tfpluginsdk.go:127 +0x88
github.com/crossplane/crossplane-runtime/pkg/reconciler/managed.(*Reconciler).Reconcile(0x400d793a00, {0x1dea72b8, 0x4002793ec0}, {{{0x0, 0x0}, {0x400ffc7788, 0x12}}})
    github.com/crossplane/crossplane-runtime@v1.16.0-rc.2.0.20240510094504-3f697876fa57/pkg/reconciler/managed/reconciler.go:914 +0x1a94
github.com/crossplane/crossplane-runtime/pkg/ratelimiter.(*Reconciler).Reconcile(0x400d78d680, {0x1dea72b8, 0x4002793ec0}, {{{0x0?, 0x5?}, {0x400ffc7788?, 0x40060e0d08?}}})
    github.com/crossplane/crossplane-runtime@v1.16.0-rc.2.0.20240510094504-3f697876fa57/pkg/ratelimiter/reconciler.go:54 +0x124
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x1ded7a50?, {0x1dea72b8?, 0x4002793ec0?}, {{{0x0?, 0xb?}, {0x400ffc7788?, 0x0?}}})
    sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go:119 +0x80
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0x400d7c4140, {0x1dea72f0, 0x400149a780}, {0x19402180, 0x400781c1a0})
    sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go:316 +0x2d0
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0x400d7c4140, {0x1dea72f0, 0x400149a780})
    sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go:266 +0x158
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
    sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go:227 +0x70
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2 in goroutine 4008
    sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go:223 +0x400
```

### Relevant Error Output Snippet

```shell
update failed: async update failed: recovered from panic: value is null
```

### Crossplane Version

1.18.0

### Provider Version

1.17.0

### Kubernetes Distribution

k3d

**Comment by turkenf** [comment]
Hi @tyu0912,

Thank you for bringing up this. This issue can be reproducible with our [base](https://github.com/crossplane-contrib/provider-upjet-aws/blob/main/examples/ec2/v1beta1/instance.yaml) example.
```
- lastTransitionTime: "2024-11-30T10:26:16Z"
    message: 'update failed: async update failed: recovered from panic: value is null'
    reason: ReconcileError
    status: "False"
    type: Synced
```

**Comment by tyu0912** [comment]
Appreciate the confirmation. Let me know if there's any assistance I can provide.

**Comment by mergenci** [comment]
I discovered that, in my local environment, restarting the provider resolved the issue for the resources, creation of which had failed. Such behavior indicates that we could be able to address the issue without any upstream fixes.

Unfortunately, the issue persists in the Terraform provider AWS v5.78.0.

**Comment by mergenci** [comment]
I explained how and why the panic occurs in my fix PR in our Terraform provider fork: https://github.com/upbound/terraform-provider-aws/pull/279 The fix is in a code path common to all resources, so we might want to get upstream approval before consuming it, just to be on the safe side. Consuming it won't be enough either. There's a perpetual resource diff that I've already resolved. I'll include it in the consumption PR.

**Comment by tyu0912** [comment]
Ah interesting, so there's a couple things then. The traversal of `d.GetOk` vs `tags.ResolveDuplicates` and because the latter returns `d.state.RawConfig.v["root_block_device"]` which is Nil, this is a case we don't check for prior to `value.LengthInt()` and that's why it panics.
