### ISSUE TITLE
[controller-runtime] log.SetLogger(...) was never called, logs will not be displayed

### ISSUE THREAD

**Issue by callum-stakater** [crossplane-contrib/provider-upjet-aws#854]
Im getting these stack traces on all the aws-family-provider pods (parent and child providers) and am not able to find any info specific to crossplane and the aws providers how to fix it but a general google search does turn up quite a few results of other projects that have addressed the same:

Crossplane 1.13.2
All AWS providers 0.39.0
On EKS 1.27

```
upbound-provider-aws-iam-e4667f1b5f01-64ffb98885-d49x4 provider-aws-iam I0830 18:11:01.576853       1 leaderelection.go:255] successfully acquired lease crossplane/crossplane-leader-election-provider-aws-iam
upbound-provider-aws-iam-e4667f1b5f01-64ffb98885-d49x4 provider-aws-iam [controller-runtime] log.SetLogger(...) was never called, logs will not be displayed:
upbound-provider-aws-iam-e4667f1b5f01-64ffb98885-d49x4 provider-aws-iam goroutine 3562 [running]:
upbound-provider-aws-iam-e4667f1b5f01-64ffb98885-d49x4 provider-aws-iam runtime/debug.Stack()
upbound-provider-aws-iam-e4667f1b5f01-64ffb98885-d49x4 provider-aws-iam         runtime/debug/stack.go:24 +0x64
upbound-provider-aws-iam-e4667f1b5f01-64ffb98885-d49x4 provider-aws-iam sigs.k8s.io/controller-runtime/pkg/log.eventuallyFulfillRoot()
upbound-provider-aws-iam-e4667f1b5f01-64ffb98885-d49x4 provider-aws-iam         sigs.k8s.io/controller-runtime@v0.15.0/pkg/log/log.go:59 +0x104
upbound-provider-aws-iam-e4667f1b5f01-64ffb98885-d49x4 provider-aws-iam sigs.k8s.io/controller-runtime/pkg/log.(*delegatingLogSink).Enabled(0x40006230c0, 0x4007691040?)
upbound-provider-aws-iam-e4667f1b5f01-64ffb98885-d49x4 provider-aws-iam         sigs.k8s.io/controller-runtime@v0.15.0/pkg/log/deleg.go:111 +0x30
upbound-provider-aws-iam-e4667f1b5f01-64ffb98885-d49x4 provider-aws-iam github.com/go-logr/logr.Logger.Enabled(...)
upbound-provider-aws-iam-e4667f1b5f01-64ffb98885-d49x4 provider-aws-iam         github.com/go-logr/logr@v1.2.4/logr.go:261
upbound-provider-aws-iam-e4667f1b5f01-64ffb98885-d49x4 provider-aws-iam github.com/go-logr/logr.Logger.Info({{0x41353c8?, 0x40006230c0?}, 0x4000683520?}, {0x4004e63650, 0x69}, {0x400014b2c0, 0x6, 0x6})
upbound-provider-aws-iam-e4667f1b5f01-64ffb98885-d49x4 provider-aws-iam         github.com/go-logr/logr@v1.2.4/logr.go:274 +0x5c
upbound-provider-aws-iam-e4667f1b5f01-64ffb98885-d49x4 provider-aws-iam sigs.k8s.io/controller-runtime/pkg/internal/recorder.(*Provider).getBroadcaster.func1.1(0x4004647b80)
upbound-provider-aws-iam-e4667f1b5f01-64ffb98885-d49x4 provider-aws-iam         sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/recorder/recorder.go:104 +0x200
upbound-provider-aws-iam-e4667f1b5f01-64ffb98885-d49x4 provider-aws-iam k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartEventWatcher.func1()
upbound-provider-aws-iam-e4667f1b5f01-64ffb98885-d49x4 provider-aws-iam         k8s.io/client-go@v0.27.3/tools/record/event.go:327 +0x98
upbound-provider-aws-iam-e4667f1b5f01-64ffb98885-d49x4 provider-aws-iam created by k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartEventWatcher
upbound-provider-aws-iam-e4667f1b5f01-64ffb98885-d49x4 provider-aws-iam         k8s.io/client-go@v0.27.3/tools/record/event.go:318 +0x138
upbound-provider-aws-s3-e6123c010ecc-7b8c456f55-q42g4 provider-aws-s3 I0830 18:11:09.938941       1 leaderelection.go:255] successfully acquired lease crossplane/crossplane-leader-election-provider-aws-s3
upbound-provider-aws-s3-e6123c010ecc-7b8c456f55-q42g4 provider-aws-s3 [controller-runtime] log.SetLogger(...) was never called, logs will not be displayed:
upbound-provider-aws-s3-e6123c010ecc-7b8c456f55-q42g4 provider-aws-s3 goroutine 3556 [running]:
upbound-provider-aws-s3-e6123c010ecc-7b8c456f55-q42g4 provider-aws-s3 runtime/debug.Stack()
upbound-provider-aws-s3-e6123c010ecc-7b8c456f55-q42g4 provider-aws-s3   runtime/debug/stack.go:24 +0x65
upbound-provider-aws-s3-e6123c010ecc-7b8c456f55-q42g4 provider-aws-s3 sigs.k8s.io/controller-runtime/pkg/log.eventuallyFulfillRoot()
upbound-provider-aws-s3-e6123c010ecc-7b8c456f55-q42g4 provider-aws-s3   sigs.k8s.io/controller-runtime@v0.15.0/pkg/log/log.go:59 +0xbd
upbound-provider-aws-s3-e6123c010ecc-7b8c456f55-q42g4 provider-aws-s3 sigs.k8s.io/controller-runtime/pkg/log.(*delegatingLogSink).Enabled(0xc00068f540, 0xc000100000?)
upbound-provider-aws-s3-e6123c010ecc-7b8c456f55-q42g4 provider-aws-s3   sigs.k8s.io/controller-runtime@v0.15.0/pkg/log/deleg.go:111 +0x3d
upbound-provider-aws-s3-e6123c010ecc-7b8c456f55-q42g4 provider-aws-s3 github.com/go-logr/logr.Logger.Enabled(...)
upbound-provider-aws-s3-e6123c010ecc-7b8c456f55-q42g4 provider-aws-s3   github.com/go-logr/logr@v1.2.4/logr.go:261
upbound-provider-aws-s3-e6123c010ecc-7b8c456f55-q42g4 provider-aws-s3 github.com/go-logr/logr.Logger.Info({{0x48099c8?, 0xc00068f540?}, 0x2a?}, {0xc004ce5960, 0x68}, {0xc0002ff920, 0x6, 0x6})
upbound-provider-aws-s3-e6123c010ecc-7b8c456f55-q42g4 provider-aws-s3   github.com/go-logr/logr@v1.2.4/logr.go:274 +0x78
upbound-provider-aws-s3-e6123c010ecc-7b8c456f55-q42g4 provider-aws-s3 sigs.k8s.io/controller-runtime/pkg/internal/recorder.(*Provider).getBroadcaster.func1.1(0xc003b85180)
upbound-provider-aws-s3-e6123c010ecc-7b8c456f55-q42g4 provider-aws-s3   sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/recorder/recorder.go:104 +0x1ed
upbound-provider-aws-s3-e6123c010ecc-7b8c456f55-q42g4 provider-aws-s3 k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartEventWatcher.func1()
upbound-provider-aws-s3-e6123c010ecc-7b8c456f55-q42g4 provider-aws-s3   k8s.io/client-go@v0.27.3/tools/record/event.go:327 +0xa2
upbound-provider-aws-s3-e6123c010ecc-7b8c456f55-q42g4 provider-aws-s3 created by k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartEventWatcher
upbound-provider-aws-s3-e6123c010ecc-7b8c456f55-q42g4 provider-aws-s3   k8s.io/client-go@v0.27.3/tools/record/event.go:318 +0x13d
upbound-provider-aws-sns-5231208b0968-6ddf6d7c75-96q26 provider-aws-sns I0830 18:11:18.993215       1 leaderelection.go:255] successfully acquired lease crossplane/crossplane-leader-election-provider-aws-sns
upbound-provider-aws-sns-5231208b0968-6ddf6d7c75-96q26 provider-aws-sns [controller-runtime] log.SetLogger(...) was never called, logs will not be displayed:
upbound-provider-aws-sns-5231208b0968-6ddf6d7c75-96q26 provider-aws-sns goroutine 3548 [running]:
upbound-provider-aws-sns-5231208b0968-6ddf6d7c75-96q26 provider-aws-sns runtime/debug.Stack()
upbound-provider-aws-sns-5231208b0968-6ddf6d7c75-96q26 provider-aws-sns         runtime/debug/stack.go:24 +0x64
upbound-provider-aws-sns-5231208b0968-6ddf6d7c75-96q26 provider-aws-sns sigs.k8s.io/controller-runtime/pkg/log.eventuallyFulfillRoot()
upbound-provider-aws-sns-5231208b0968-6ddf6d7c75-96q26 provider-aws-sns         sigs.k8s.io/controller-runtime@v0.15.0/pkg/log/log.go:59 +0x104
upbound-provider-aws-sns-5231208b0968-6ddf6d7c75-96q26 provider-aws-sns sigs.k8s.io/controller-runtime/pkg/log.(*delegatingLogSink).Enabled(0x400068ef40, 0x40065a7150?)
upbound-provider-aws-sns-5231208b0968-6ddf6d7c75-96q26 provider-aws-sns         sigs.k8s.io/controller-runtime@v0.15.0/pkg/log/deleg.go:111 +0x30
upbound-provider-aws-sns-5231208b0968-6ddf6d7c75-96q26 provider-aws-sns github.com/go-logr/logr.Logger.Enabled(...)
upbound-provider-aws-sns-5231208b0968-6ddf6d7c75-96q26 provider-aws-sns         github.com/go-logr/logr@v1.2.4/logr.go:261
upbound-provider-aws-sns-5231208b0968-6ddf6d7c75-96q26 provider-aws-sns github.com/go-logr/logr.Logger.Info({{0x410db68?, 0x400068ef40?}, 0x4007bc0820?}, {0x400662f2d0, 0x69}, {0x40009d1f80, 0x6, 0x6})
upbound-provider-aws-sns-5231208b0968-6ddf6d7c75-96q26 provider-aws-sns         github.com/go-logr/logr@v1.2.4/logr.go:274 +0x5c
upbound-provider-aws-sns-5231208b0968-6ddf6d7c75-96q26 provider-aws-sns sigs.k8s.io/controller-runtime/pkg/internal/recorder.(*Provider).getBroadcaster.func1.1(0x4006620280)
upbound-provider-aws-sns-5231208b0968-6ddf6d7c75-96q26 provider-aws-sns         sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/recorder/recorder.go:104 +0x200
upbound-provider-aws-sns-5231208b0968-6ddf6d7c75-96q26 provider-aws-sns k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartEventWatcher.func1()
upbound-provider-aws-sns-5231208b0968-6ddf6d7c75-96q26 provider-aws-sns         k8s.io/client-go@v0.27.3/tools/record/event.go:327 +0x98
upbound-provider-aws-sns-5231208b0968-6ddf6d7c75-96q26 provider-aws-sns created by k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartEventWatcher
upbound-provider-aws-sns-5231208b0968-6ddf6d7c75-96q26 provider-aws-sns         k8s.io/client-go@v0.27.3/tools/record/event.go:318 +0x138
upbound-provider-family-aws-63c2dfd019ef-79d98dd97b-rsrcg provider-family-aws I0830 18:11:23.378607       1 leaderelection.go:255] successfully acquired lease crossplane/crossplane-leader-election-provider-aws-config
upbound-provider-family-aws-63c2dfd019ef-79d98dd97b-rsrcg provider-family-aws [controller-runtime] log.SetLogger(...) was never called, logs will not be displayed:
upbound-provider-family-aws-63c2dfd019ef-79d98dd97b-rsrcg provider-family-aws goroutine 3598 [running]:
upbound-provider-family-aws-63c2dfd019ef-79d98dd97b-rsrcg provider-family-aws runtime/debug.Stack()
upbound-provider-family-aws-63c2dfd019ef-79d98dd97b-rsrcg provider-family-aws   runtime/debug/stack.go:24 +0x65
upbound-provider-family-aws-63c2dfd019ef-79d98dd97b-rsrcg provider-family-aws sigs.k8s.io/controller-runtime/pkg/log.eventuallyFulfillRoot()
upbound-provider-family-aws-63c2dfd019ef-79d98dd97b-rsrcg provider-family-aws   sigs.k8s.io/controller-runtime@v0.15.0/pkg/log/log.go:59 +0xbd
upbound-provider-family-aws-63c2dfd019ef-79d98dd97b-rsrcg provider-family-aws sigs.k8s.io/controller-runtime/pkg/log.(*delegatingLogSink).Enabled(0xc000b14380, 0xc000600000?)
upbound-provider-family-aws-63c2dfd019ef-79d98dd97b-rsrcg provider-family-aws   sigs.k8s.io/controller-runtime@v0.15.0/pkg/log/deleg.go:111 +0x3d
upbound-provider-family-aws-63c2dfd019ef-79d98dd97b-rsrcg provider-family-aws github.com/go-logr/logr.Logger.Enabled(...)
upbound-provider-family-aws-63c2dfd019ef-79d98dd97b-rsrcg provider-family-aws   github.com/go-logr/logr@v1.2.4/logr.go:261
upbound-provider-family-aws-63c2dfd019ef-79d98dd97b-rsrcg provider-family-aws github.com/go-logr/logr.Logger.Info({{0x471fa28?, 0xc000b14380?}, 0x0?}, {0xc005fb3b20, 0x6c}, {0xc0003390e0, 0x6, 0x6})
upbound-provider-family-aws-63c2dfd019ef-79d98dd97b-rsrcg provider-family-aws   github.com/go-logr/logr@v1.2.4/logr.go:274 +0x78
upbound-provider-family-aws-63c2dfd019ef-79d98dd97b-rsrcg provider-family-aws sigs.k8s.io/controller-runtime/pkg/internal/recorder.(*Provider).getBroadcaster.func1.1(0xc005fae500)
upbound-provider-family-aws-63c2dfd019ef-79d98dd97b-rsrcg provider-family-aws   sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/recorder/recorder.go:104 +0x1ed
upbound-provider-family-aws-63c2dfd019ef-79d98dd97b-rsrcg provider-family-aws k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartEventWatcher.func1()
upbound-provider-family-aws-63c2dfd019ef-79d98dd97b-rsrcg provider-family-aws   k8s.io/client-go@v0.27.3/tools/record/event.go:327 +0xa2
upbound-provider-family-aws-63c2dfd019ef-79d98dd97b-rsrcg provider-family-aws created by k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartEventWatcher
upbound-provider-family-aws-63c2dfd019ef-79d98dd97b-rsrcg provider-family-aws   k8s.io/client-go@v0.27.3/tools/record/event.go:318 +0x13d
```

**Comment by korenyoni** [comment]
I had this same issue when the crossplane controller itself had the `--debug` argument but the AWS providers did not. Adding `--debug` to the controllerconfig referenced by the providers resolved it. Seems like some uncaught exception though, so still a bug probably.

**Comment by turkenf** [comment]
@callum-stakater, could you please give more information to reproduce this issue; reproduction steps, expected behavior, etc?

**Comment by turkenh** [comment]
We had the same issue in core and fixed with this PR https://github.com/crossplane/crossplane/pull/4403

A similar fix could be applied here.
