### ISSUE TITLE
provider-aws crashes with fatal error: concurrent map iteration and map write

### ISSUE THREAD

**Issue by alexinthesky** [crossplane-contrib/provider-upjet-aws#939]
### What happened?

provider-aws randomly crashed when a particular rolepolicyattachement is reconciliated / refreshed

### How can we reproduce it?

create a bunch of rolepolicyattachements
```apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: node-group-ssm
spec:
  forProvider:
    policyArn: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
    role: node-group
    roleRef:
      name: node-group
    roleSelector:
      matchControllerRef: true
      matchLabels:
        role: nodegroup
  providerConfigRef:
    name: XXXXX
```

wait for the crash:

```
DEBUG	provider-aws	refresh ended	{"workspace": "/tmp/6efc55bd-8702-4819-8487-81c070dc8bab", "out": "{\"@level\":\"info\",\"@message\":\"Terraform 1.5.5\",\"@module\":\"terraform.ui\",\"@timestamp\":\"2023-10-26T00:56:57.103871Z\",\"terraform\":\"1.5.5\",\"type\":\"version\",\"ui\":\"1.1\"}\n{\"@level\":\"info\",\"@message\":\"aws_iam_role_policy_attachment.node-group-ssm: Refreshing state... [id=node-group-20231026003648468500000001]\",\"@module\":\"terraform.ui\",\"@timestamp\":\"2023-10-26T00:56:58.323152Z\",\"hook\":{\"resource\":{\"addr\":\"aws_iam_role_policy_attachment.node-group-ssm\",\"module\":\"\",\"resource\":\"aws_iam_role_policy_attachment.node-group-ssm\",\"implied_provider\":\"aws\",\"resource_type\":\"aws_iam_role_policy_attachment\",\"resource_name\":\"node-group-ssm\",\"resource_key\":null},\"id_key\":\"id\",\"id_value\":\"node-group-20231026003648468500000001\"},\"type\":\"refresh_start\"}\n{\"@level\":\"info\",\"@message\":\"aws_iam_role_policy_attachment.node-group-ssm: Refresh complete\",\"@module\":\"terraform.ui\",\"@timestamp\":\"2023-10-26T00:56:58.698828Z\",\"hook\":{\"resource\":{\"addr\":\"aws_iam_role_policy_attachment.node-group-ssm\",\"module\":\"\",\"resource\":\"aws_iam_role_policy_attachment.node-group-ssm\",\"implied_provider\":\"aws\",\"resource_type\":\"aws_iam_role_policy_attachment\",\"resource_name\":\"node-group-ssm\",\"resource_key\":null}},\"type\":\"refresh_complete\"}\n{\"@level\":\"info\",\"@message\":\"aws_iam_role_policy_attachment.node-group-ssm: Drift detected (delete)\",\"@module\":\"terraform.ui\",\"@timestamp\":\"2023-10-26T00:56:58.699188Z\",\"change\":{\"resource\":{\"addr\":\"aws_iam_role_policy_attachment.node-group-ssm\",\"module\":\"\",\"resource\":\"aws_iam_role_policy_attachment.node-group-ssm\",\"implied_provider\":\"aws\",\"resource_type\":\"aws_iam_role_policy_attachment\",\"resource_name\":\"node-group-ssm\",\"resource_key\":null},\"action\":\"delete\"},\"type\":\"resource_drift\"}\n{\"@level\":\"info\",\"@message\":\"Plan: 0 to add, 0 to change, 0 to destroy.\",\"@module\":\"terraform.ui\",\"@timestamp\":\"2023-10-26T00:56:58.699246Z\",\"changes\":{\"add\":0,\"change\":0,\"import\":0,\"remove\":0,\"operation\":\"plan\"},\"type\":\"change_summary\"}\n{\"@level\":\"info\",\"@message\":\"Apply complete! Resources: 0 added, 0 changed, 0 destroyed.\",\"@module\":\"terraform.ui\",\"@timestamp\":\"2023-10-26T00:56:58.702966Z\",\"changes\":{\"add\":0,\"change\":0,\"import\":0,\"remove\":0,\"operation\":\"apply\"},\"type\":\"change_summary\"}\n{\"@level\":\"info\",\"@message\":\"Outputs: 0\",\"@module\":\"terraform.ui\",\"@timestamp\":\"2023-10-26T00:56:58.702993Z\",\"outputs\":{},\"type\":\"outputs\"}\n"}
DEBUG	provider-aws	Reusing the provider runner	{"handle": "69a6a4ff7feee5fc2fd6a15baf8a6037a1a99142065303743c17b2785979298b", "ttl": 100, "ttlMargin": 0.1, "invocationCount": 56, "inUse": 0}
DEBUG	provider-aws	Shared gRPC server is running...	{"handle": "69a6a4ff7feee5fc2fd6a15baf8a6037a1a99142065303743c17b2785979298b", "ttl": 100, "ttlMargin": 0.1, "nativeProviderPath": "/terraform/provider-mirror/registry.terraform.io/hashicorp/aws/4.67.0/linux_arm64/terraform-provider-aws_v4.67.0_x5", "nativeProviderArgs": [], "reattachConfig": "{\"registry.terraform.io/hashicorp/aws\":{\"Protocol\":\"grpc\",\"ProtocolVersion\":5,\"Pid\":1,\"Test\": true,\"Addr\":{\"Network\": \"unix\",\"String\": \"/tmp/plugin1053274016\"}}}"}
DEBUG	provider-aws	Running terraform	{"workspace": "/tmp/6efc55bd-8702-4819-8487-81c070dc8bab", "args": ["apply", "-auto-approve", "-input=false", "-lock=false", "-json"]}
DEBUG	provider-aws	Successfully requested creation of external resource	{"controller": "managed/iam.aws.upbound.io/v1beta1, kind=rolepolicyattachment", "request": {"name":"node-group-ssm"}, "uid": "6efc55bd-8702-4819-8487-81c070dc8bab", "version": "417680434", "external-name": "node-group-20231026003648468500000001", "external-name": "node-group-20231026003648468500000001"}
DEBUG	events	Successfully requested creation of external resource	{"type": "Normal", "object": {"kind":"RolePolicyAttachment","name":"node-group-ssm","uid":"6efc55bd-8702-4819-8487-81c070dc8bab","apiVersion":"iam.aws.upbound.io/v1beta1","resourceVersion":"417725418"}, "reason": "CreatedExternalResource"}
DEBUG	provider-aws	Calling the inner handler for Update event.	{"gvk": "iam.aws.upbound.io/v1beta1, Kind=RolePolicyAttachment", "name": "node-group-ssm", "queueLength": 0}
DEBUG	provider-aws	Reconciling	{"controller": "managed/iam.aws.upbound.io/v1beta1, kind=rolepolicyattachment", "request": {"name":"node-group-ssm"}}
fatal error: concurrent map iteration and map write


goroutine 12285 [running]:
k8s.io/apimachinery/pkg/apis/meta/v1.(*ObjectMeta).DeepCopyInto(0x4017992c60, 0x4017992e20)
	k8s.io/apimachinery@v0.27.3/pkg/apis/meta/v1/zz_generated.deepcopy.go:689 +0x304
github.com/upbound/provider-aws/apis/iam/v1beta1.(*RolePolicyAttachment).DeepCopyInto(0x4017992c40, 0x4017992e00)
	github.com/upbound/provider-aws/apis/iam/v1beta1/zz_generated.deepcopy.go:2524 +0xd8
github.com/upbound/provider-aws/apis/iam/v1beta1.(*RolePolicyAttachment).DeepCopy(...)
	github.com/upbound/provider-aws/apis/iam/v1beta1/zz_generated.deepcopy.go:2535
github.com/upbound/provider-aws/apis/iam/v1beta1.(*RolePolicyAttachment).DeepCopyObject(0x4017992c40?)
	github.com/upbound/provider-aws/apis/iam/v1beta1/zz_generated.deepcopy.go:2541 +0x44
sigs.k8s.io/controller-runtime/pkg/cache/internal.(*CacheReader).Get(0x40006ef040, {0x488de90?, 0x4015653320?}, {{0x0?, 0x12?}, {0x401c778aa0?, 0x7?}}, {0x48cdd90, 0x4000bacfc0}, {0x4870aa8?, ...})
	sigs.k8s.io/controller-runtime@v0.15.0/pkg/cache/internal/cache_reader.go:88 +0x114
sigs.k8s.io/controller-runtime/pkg/cache.(*informerCache).Get(0x4000158da0, {0x488de90, 0x4015653320}, {{0x0?, 0x400ded5f98?}, {0x401c778aa0?, 0x3c4dd60?}}, {0x48cdd90?, 0x4000bacfc0?}, {0xa9118?, ...})
	sigs.k8s.io/controller-runtime@v0.15.0/pkg/cache/informer_cache.go:70 +0x13c
sigs.k8s.io/controller-runtime/pkg/client.(*client).Get(0x40004965a0, {0x488de90, 0x4015653320}, {{0x0?, 0x40169c3a40?}, {0x401c778aa0?, 0x0?}}, {0x48cdd90?, 0x4000bacfc0?}, {0x0, ...})
	sigs.k8s.io/controller-runtime@v0.15.0/pkg/client/client.go:341 +0x300
github.com/crossplane/crossplane-runtime/pkg/reconciler/managed.(*Reconciler).Reconcile(0x4000a9d590, {0x488dec8, 0x40152b0f30}, {{{0x0?, 0x10?}, {0x401c778aa0?, 0x40152b0ed0?}}})
	github.com/crossplane/crossplane-runtime@v0.20.0/pkg/reconciler/managed/reconciler.go:704 +0x20c
github.com/crossplane/crossplane-runtime/pkg/ratelimiter.(*Reconciler).Reconcile(0x4000aa3590, {0x488dec8, 0x40152b0f30}, {{{0x0?, 0x30?}, {0x401c778aa0?, 0xffff8a835301?}}})
	github.com/crossplane/crossplane-runtime@v0.20.0/pkg/ratelimiter/reconciler.go:54 +0x124
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x488dec8?, {0x488dec8?, 0x40152b0f30?}, {{{0x0?, 0x3294440?}, {0x401c778aa0?, 0x0?}}})
	sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:118 +0x8c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0x4000aaae60, {0x488de20, 0x400023d2c0}, {0x37b51e0?, 0x400a0f2da0?})
	sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:314 +0x2f0
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0x4000aaae60, {0x488de20, 0x400023d2c0})
	sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:265 +0x1b0
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:226 +0x74
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:222 +0x294

goroutine 1 [select, 1399 minutes]:
sigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).Start(0x4000682820, {0x488de20, 0x40010b2cc0})
	sigs.k8s.io/controller-runtime@v0.15.0/pkg/manager/internal.go:509 +0x698
main.main()
	github.com/upbound/provider-aws/cmd/provider/monolith/zz_main.go:148 +0x2afc

goroutine 6368 [select]:
k8s.io/client-go/util/workqueue.(*delayingType).waitingLoop(0x40023620c0)
	k8s.io/client-go@v0.27.3/util/workqueue/delaying_queue.go:276 +0x258
created by k8s.io/client-go/util/workqueue.newDelayingQueue
	k8s.io/client-go@v0.27.3/util/workqueue/delaying_queue.go:113 +0x208

goroutine 3633 [chan receive, 1399 minutes]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start(0x4000310c80, {0x488de20, 0x400023d2c0})
	sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:238 +0x1d0
sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func1(0x4000908640)
	sigs.k8s.io/controller-runtime@v0.15.0/pkg/manager/runnable_group.go:219 +0xd8
created by sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile
	sigs.k8s.io/controller-runtime@v0.15.0/pkg/manager/runnable_group.go:203 +0x220

goroutine 1264 [chan receive, 1399 minutes]:
sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile(0x4000496c60)
	sigs.k8s.io/controller-runtime@v0.15.0/pkg/manager/runnable_group.go:179 +0x3c
created by sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).Start.func1
	sigs.k8s.io/controller-runtime@v0.15.0/pkg/manager/runnable_group.go:132 +0xb4

goroutine 12790 [select, 1399 minutes]:
k8s.io/client-go/tools/cache.(*processorListener).pop(0x4009557a70)
	k8s.io/client-go@v0.27.3/tools/cache/shared_informer.go:938 +0xe0
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
	k8s.io/apimachinery@v0.27.3/pkg/util/wait/wait.go:72 +0x58
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	k8s.io/apimachinery@v0.27.3/pkg/util/wait/wait.go:70 +0x84

goroutine 1816 [chan receive, 1399 minutes]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start(0x40001ceaa0, {0x488de20, 0x400023d2c0})
	sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:238 +0x1d0
sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func1(0x40053a3a60)
	sigs.k8s.io/controller-runtime@v0.15.0/pkg/manager/runnable_group.go:219 +0xd8
created by sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile
	sigs.k8s.io/controller-runtime@v0.15.0/pkg/manager/runnable_group.go:203 +0x220

goroutine 2463 [chan receive, 1399 minutes]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1()
	sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:162 +0x38
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
	sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:161 +0x184

goroutine 10765 [sync.Cond.Wait, 1399 minutes]:
sync.runtime_notifyListWait(0x4001f21c10, 0x4)
	runtime/sema.go:517 +0x160
sync.(*Cond).Wait(0x4001f21c00)
	sync/cond.go:70 +0xd0
k8s.io/client-go/util/workqueue.(*Type).Get(0x4001f54900)
	k8s.io/client-go@v0.27.3/util/workqueue/queue.go:200 +0x90
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0x40008b2f00, {0x488de20, 0x400023d2c0})
	sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:248 +0x4c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:226 +0x74
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:222 +0x294

goroutine 2462 [select]:
k8s.io/client-go/util/workqueue.(*delayingType).waitingLoop(0x40073c63c0)
	k8s.io/client-go@v0.27.3/util/workqueue/delaying_queue.go:276 +0x258
created by k8s.io/client-go/util/workqueue.newDelayingQueue
	k8s.io/client-go@v0.27.3/util/workqueue/delaying_queue.go:113 +0x208

goroutine 2461 [chan receive]:
k8s.io/client-go/util/workqueue.(*Type).updateUnfinishedWorkLoop(0x40073c6240)
	k8s.io/client-go@v0.27.3/util/workqueue/queue.go:314 +0x94
created by k8s.io/client-go/util/workqueue.newQueue
	k8s.io/client-go@v0.27.3/util/workqueue/queue.go:106 +0x1c8

goroutine 2459 [chan receive, 1399 minutes]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start(0x4000310fa0, {0x488de20, 0x400023d2c0})
	sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:238 +0x1d0
sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func1(0x4000908ea0)
	sigs.k8s.io/controller-runtime@v0.15.0/pkg/manager/runnable_group.go:219 +0xd8
created by sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile
	sigs.k8s.io/controller-runtime@v0.15.0/pkg/manager/runnable_group.go:203 +0x220

goroutine 1817 [chan receive, 1399 minutes]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start(0x40001cee60, {0x488de20, 0x400023d2c0})
	sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:238 +0x1d0
sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func1(0x40053a3ce0)
	sigs.k8s.io/controller-runtime@v0.15.0/pkg/manager/runnable_group.go:219 +0xd8
created by sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile
	sigs.k8s.io/controller-runtime@v0.15.0/pkg/manager/runnable_group.go:203 +0x220

goroutine 6570 [chan receive]:
k8s.io/client-go/util/workqueue.(*Type).updateUnfinishedWorkLoop(0x40026443c0)
	k8s.io/client-go@v0.27.3/util/workqueue/queue.go:314 +0x94
created by k8s.io/client-go/util/workqueue.newQueue
	k8s.io/client-go@v0.27.3/util/workqueue/queue.go:106 +0x1c8

goroutine 3619 [chan receive, 20 minutes]:
github.com/upbound/upjet/pkg/terraform.(*WorkspaceStore).reportTFProcesses(0x4000529800, 0x400006e4c0?)
	github.com/upbound/upjet@v0.10.0/pkg/terraform/store.go:328 +0x128
created by github.com/upbound/upjet/pkg/terraform.NewWorkspaceStore
	github.com/upbound/upjet@v0.10.0/pkg/terraform/store.go:200 +0x1e8

goroutine 6357 [chan receive, 1399 minutes]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1()
	sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:162 +0x38
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
	sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:161 +0x184

goroutine 2327 [chan receive, 1399 minutes]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start(0x400097d220, {0x488de20, 0x400023d2c0})
	sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:238 +0x1d0
sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func1(0x400088b1c0)
	sigs.k8s.io/controller-runtime@v0.15.0/pkg/manager/runnable_group.go:219 +0xd8
created by sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile
	sigs.k8s.io/controller-runtime@v0.15.0/pkg/manager/runnable_group.go:203 +0x220

goroutine 3525 [chan receive, 1399 minutes]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start(0x400097caa0, {0x488de20, 0x400023d2c0})
	sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:238 +0x1d0`
### What environment did it happen in?
```
* Crossplane Version: v1.13.2
* Provider Version: 0.40.0
* Kubernetes Version: v1.27.6 
* Kubernetes Distribution: EKS

**Comment by turkenf** [comment]
@alexinthesky, could you please try version 0.43.0 and let us know?

**Comment by alexinthesky** [comment]
yep as soon as we can. If it's some kind of race condition I guess the jitter will lower the odds of this happening !
