### ISSUE TITLE
EKS provider pod goes into CrashLoopBackOff while deploying EKS Cluster in runtime

### ISSUE THREAD

**Issue by kumudhanrajan18** [crossplane-contrib/provider-upjet-aws#986]
### What happened?

When i tried to deploy EKS Cluster using Composition, the EKS Provider pod running on v0.44.0 went into CrashLoopBackOff state.  
This was the stack trace/Pod Logs:

```
`2023-11-28T16:33:56Z	DEBUG	provider-aws	Calling the inner handler for Update event.	{"gvk": "eks.aws.upbound.io/v1beta1, Kind=Cluster", "name": "eks-gw5pt", "queueLength": 0}
2023-11-28T16:33:56Z	DEBUG	provider-aws	Connecting to the service provider	{"uid": "cfa4a877-c0bb-4626-a046-4977a255f8d3", "name": "eks-gw5pt", "gvk": "eks.aws.upbound.io/v1beta1, Kind=Cluster"}
2023-11-28T16:33:56Z	DEBUG	provider-aws	Instance state not found in cache, reconstructing...	{"uid": "cfa4a877-c0bb-4626-a046-4977a255f8d3", "name": "eks-gw5pt", "gvk": "eks.aws.upbound.io/v1beta1, Kind=Cluster"}
2023-11-28T16:33:56Z	DEBUG	provider-aws	Observing the external resource	{"uid": "cfa4a877-c0bb-4626-a046-4977a255f8d3", "name": "eks-gw5pt", "gvk": "eks.aws.upbound.io/v1beta1, Kind=Cluster"}
2023/11/28 16:33:56 [WARN] EKS Cluster (eks-gw5pt) not found, removing from state
2023-11-28T16:33:56Z	DEBUG	provider-aws	Diff detected	{"uid": "cfa4a877-c0bb-4626-a046-4977a255f8d3", "name": "eks-gw5pt", "gvk": "eks.aws.upbound.io/v1beta1, Kind=Cluster", "instanceDiff": "*terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{\"arn\":*terraform.ResourceAttrDiff{Old:\"\", New:\"\", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, \"certificate_authority.#\":*terraform.ResourceAttrDiff{Old:\"\", New:\"\", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, \"cluster_id\":*terraform.ResourceAttrDiff{Old:\"\", New:\"\", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, \"created_at\":*terraform.ResourceAttrDiff{Old:\"\", New:\"\", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, \"encryption_config.#\":*terraform.ResourceAttrDiff{Old:\"0\", New:\"2\", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, \"encryption_config.0.provider.#\":*terraform.ResourceAttrDiff{Old:\"0\", New:\"1\", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, \"encryption_config.0.provider.0.key_arn\":*terraform.ResourceAttrDiff{Old:\"\", New:\"arn:aws:kms:eu-west-1:180434619498:key/4889655a-d04a-4dac-9981-60a5b729b2eb\", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, \"encryption_config.1.resources.#\":*terraform.ResourceAttrDiff{Old:\"0\", New:\"1\", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, \"encryption_config.1.resources.2031673519\":*terraform.ResourceAttrDiff{Old:\"\", New:\"secrets\", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, \"endpoint\":*terraform.ResourceAttrDiff{Old:\"\", New:\"\", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, \"identity.#\":*terraform.ResourceAttrDiff{Old:\"\", New:\"\", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, \"kubernetes_network_config.#\":*terraform.ResourceAttrDiff{Old:\"\", New:\"\", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, \"name\":*terraform.ResourceAttrDiff{Old:\"\", New:\"eks-gw5pt\", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, \"platform_version\":*terraform.ResourceAttrDiff{Old:\"\", New:\"\", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, \"role_arn\":*terraform.ResourceAttrDiff{Old:\"\", New:\"arn:aws:iam::180434619498:role/eks-hxs9s\", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, \"status\":*terraform.ResourceAttrDiff{Old:\"\", New:\"\", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, \"tags.%\":*terraform.ResourceAttrDiff{Old:\"0\", New:\"3\", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, \"tags.crossplane-kind\":*terraform.ResourceAttrDiff{Old:\"\", New:\"cluster.eks.aws.upbound.io\", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, \"tags.crossplane-name\":*terraform.ResourceAttrDiff{Old:\"\", New:\"eks-gw5pt\", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, \"tags.crossplane-providerconfig\":*terraform.ResourceAttrDiff{Old:\"\", New:\"dev-pc\", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, \"tags_all.%\":*terraform.ResourceAttrDiff{Old:\"0\", New:\"3\", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, \"tags_all.crossplane-kind\":*terraform.ResourceAttrDiff{Old:\"\", New:\"cluster.eks.aws.upbound.io\", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, \"tags_all.crossplane-name\":*terraform.ResourceAttrDiff{Old:\"\", New:\"eks-gw5pt\", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, \"tags_all.crossplane-providerconfig\":*terraform.ResourceAttrDiff{Old:\"\", New:\"dev-pc\", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, \"version\":*terraform.ResourceAttrDiff{Old:\"\", New:\"1.28\", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, \"vpc_config.#\":*terraform.ResourceAttrDiff{Old:\"0\", New:\"3\", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, \"vpc_config.0.cluster_security_group_id\":*terraform.ResourceAttrDiff{Old:\"\", New:\"\", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, \"vpc_config.0.endpoint_private_access\":*terraform.ResourceAttrDiff{Old:\"\", New:\"true\", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, \"vpc_config.0.endpoint_public_access\":*terraform.ResourceAttrDiff{Old:\"\", New:\"true\", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, \"vpc_config.0.public_access_cidrs.#\":*terraform.ResourceAttrDiff{Old:\"\", New:\"\", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, \"vpc_config.0.vpc_id\":*terraform.ResourceAttrDiff{Old:\"\", New:\"\", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, \"vpc_config.1.cluster_security_group_id\":*terraform.ResourceAttrDiff{Old:\"\", New:\"\", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, \"vpc_config.1.endpoint_private_access\":*terraform.ResourceAttrDiff{Old:\"\", New:\"false\", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, Meta:map[string]interface {}(nil)}"}
2023-11-28T16:33:56Z	DEBUG	provider-aws	Async create starting...	{"trackerUID": "cfa4a877-c0bb-4626-a046-4977a255f8d3", "resourceName": "eks-gw5pt", "tfID": ""}
2023-11-28T16:33:56Z	DEBUG	provider-aws	Creating the external resource	{"uid": "cfa4a877-c0bb-4626-a046-4977a255f8d3", "name": "eks-gw5pt", "gvk": "eks.aws.upbound.io/v1beta1, Kind=Cluster"}
panic: runtime error: index out of range [0] with length 0

goroutine 4329 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/eks.expandProvider(...)
	github.com/hashicorp/terraform-provider-aws@v0.0.0-00010101000000-000000000000/internal/service/eks/cluster.go:732
github.com/hashicorp/terraform-provider-aws/internal/service/eks.expandEncryptionConfig({0x40077aea20?, 0x2, 0x18?})
	github.com/hashicorp/terraform-provider-aws@v0.0.0-00010101000000-000000000000/internal/service/eks/cluster.go:718 +0x344
github.com/hashicorp/terraform-provider-aws/internal/service/eks.resourceClusterCreate({0x1125a4f8?, 0x4006fd83f0}, 0x4006acf700, {0xf540f00?, 0x4000028c00})
	github.com/hashicorp/terraform-provider-aws@v0.0.0-00010101000000-000000000000/internal/service/eks/cluster.go:296 +0xc8
github.com/hashicorp/terraform-provider-aws/internal/provider.interceptedHandler[...].func1(0xffff6b4d21e0?, {0xf540f00?, 0x4000028c00?})
	github.com/hashicorp/terraform-provider-aws@v0.0.0-00010101000000-000000000000/internal/provider/intercept.go:95 +0x27c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x1125a4c0?, {0x1125a4c0?, 0x400681b950?}, 0xd?, {0xf540f00?, 0x4000028c00?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:702 +0x64
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x40016b1ce0, {0x1125a4c0, 0x400681b950}, 0x0, 0x4007df0e80, {0xf540f00, 0x4000028c00})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:837 +0x85c
github.com/crossplane/upjet/pkg/controller.(*noForkExternal).Create(0x4008f5dee0, {0x1125a4c0, 0x400681b950}, {0x112ca178?, 0x4006208800})
	github.com/crossplane/upjet@v1.0.0/pkg/controller/external_nofork.go:554 +0xb4
github.com/crossplane/upjet/pkg/controller.(*noForkAsyncExternal).Create.func1()
	github.com/crossplane/upjet@v1.0.0/pkg/controller/external_async_nofork.go:137 +0x12c
created by github.com/crossplane/upjet/pkg/controller.(*noForkAsyncExternal).Create
	github.com/crossplane/upjet@v1.0.0/pkg/controller/external_async_nofork.go:133 +0x154`
```

### What environment did it happen in?

* Crossplane Version: 1.14.2
* Provider Version: 0.44.0
* Kubernetes Version: 1.28 
* Kubernetes Distribution: EKS

**Comment by haarchri** [comment]
Can you add the managed resource ?

**Comment by kumudhanrajan18** [comment]
```
`apiVersion: eks.aws.upbound.io/v1beta1
kind: Cluster
metadata:
  annotations:
    crossplane.io/composition-resource-name: eks-cluster
    crossplane.io/external-create-pending: "2023-11-28T19:54:35Z"
    crossplane.io/external-create-succeeded: "2023-11-28T19:54:35Z"
    crossplane.io/external-name: eks-w7r5b
    meta.upbound.io/id: eks/v1beta1/cluster
  creationTimestamp: "2023-11-28T16:59:23Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generateName: eks-
  generation: 363
  labels:
    crossplane.io/claim-name: ""
    crossplane.io/claim-namespace: ""
    crossplane.io/composite: eks
    name: ci24-app01
    type: ekscluster
  name: eks-w7r5b
  ownerReferences:
  - apiVersion: gitops.k8s.aws/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: EKSCluster
    name: eks
    uid: 7b19922c-c783-4488-abb4-41815f4b0ddc
  resourceVersion: "691997"
  uid: fb1e18d6-4b63-4da6-b7de-5f464ea2103c
spec:
  deletionPolicy: Delete
  forProvider:
    region: eu-west-1
    roleArn: _role-arn_
    roleArnRef:
      name: eks-hxs9s
    roleArnSelector:
      matchLabels:
        name: app01-cluster-role
        type: role
    tags:
      crossplane-kind: cluster.eks.aws.upbound.io
      crossplane-name: eks-w7r5b
      crossplane-providerconfig: dev-pc
    version: "1.28"
    vpcConfig:
    - endpointPrivateAccess: true
    - endpointPublicAccess: true
    - subnetIdRefs:
      - name: core-network-q8mp7
      subnetIdSelector:
        matchLabels:
          access: private
          visibility: private-subnet01
      subnetIds:
      - subnet-00fbd1b2be88b18f6
  initProvider: {}
  managementPolicies:
  - '*'
  providerConfigRef:
    name: dev-pc
  writeConnectionSecretToRef:
    name: 7b19922c-c783-4488-abb4-41815f4b0ddc-ekscluster-connection
    namespace: crossplane-system
```

**Comment by haarchri** [comment]
can you check this:


```
    vpcConfig:
    - endpointPrivateAccess: true
       endpointPublicAccess: true
       subnetIdRefs:
      - name: core-network-q8mp7
      subnetIdSelector:
        matchLabels:
          access: private
          visibility: private-subnet01
```

**Comment by turkenf** [comment]
@kumudhanrajan18, is this issue still valid with the latest provider version?
